# Browser Configuration
url=https://demowebshop.tricentis.com
browser=chrome
# Credentials
EndUser_Id=ReenaVijay2@gmail.com
EndUser_Password=Reena@123
# Timeouts=
implicit_wait=10
page_load_timeout=30